config/routes.rb
Rails.application.routes.draw do
  # devise_for :professionals, path: '/professionals', path_names: {
  #                          sign_in: 'login',
  #                          sign_out: 'logout',
  #                          sign_up: 'registration'
  #                      },
  #            controllers: { registrations: 'professionals/registrations', sessions: 'professionals/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path: '/', path_names: {
                       sign_in: 'login',
                       sign_out: 'logout',
                       sign_up: 'registration'
                   },
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  authenticated :user do
    root 'home#profile', as: 'profile_index'
  end

  root 'home#index'

  get :choose_type, to: 'home#choose_type'
  get 'region_province/:id', to: 'home#get_region_province', as: 'get_region_province'
  get 'genre_sub_genre/:id', to: 'home#get_sub_genre', as: 'genre_sub_genre'
  get 'profile_sub_profile/:id', to: 'home#get_sub_profile', as: 'profile_sub_profile'
  namespace :listeners do
    resource :profile, only: [:new, :create]
    resources :registrations, only: [:new]
  end

  namespace :professionals do
    resources :registrations, only: [:new]
    resource :profile, only: [:new, :create]
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :sub_profiles
end

app/controllers/listeners/profiles_controller.rb
class Listeners::ProfilesController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = current_user
    @listener_genre = @user.listener_genres.build
  end

  def create
    @user = current_user
    # debugger
    if @user.update_attributes(genre_params)
      redirect_to new_listeners_profile_path, notice: 'Sub Genres are updated successfully.'
    end
  end

  private

  def genre_params
    params.require(:user).permit(
        listener_genres_attributes: [:id, :genre_id, :_destroy, listener_sub_genres_attributes: [:id, :sub_genre_id, :_destroy]])
  end
end

app/controllers/professionals/profiles_controller.rb
class Professionals::ProfilesController < ApplicationController
  def new
    @user = current_user
    if @user.professional_profile.nil?
      @professional_profile = @user.build_professional_profile
    else
      @professional_profile = @user.professional_profile
    end
    @professional_profile.ip_profiles.build
  end

  def create
    @user = current_user
    if @user.professional_profile.nil?
      @professional_profile = @user.build_professional_profile(professional_params)
      if @professional_profile.save
        redirect_to new_professionals_profile_path, notice: 'Profile is updated successfully.'
      else render :new
      end
    else
      @professional_profile = @user.professional_profile
      if @professional_profile.update_attributes(professional_params)
        redirect_to new_professionals_profile_path, notice: 'Profile is updated successfully.'
      else render :new
      end
    end


  end

  private

  def professional_params
    params.require(:professional_profile).permit( :hireable_lesson, :hireable_booking,
        ip_profiles_attributes: [:id, :profile_id, :profile_name, :_destroy, ip_sub_profiles_attributes: [:id, :sub_profile_id, :_destroy]]
    )
  end
end

app/controllers/professionals/registrations_controller.rb
class Professionals::RegistrationsController < ApplicationController
  def new
    session[:user_type] = ENV['PROFESSIONAL_TYPE']
    redirect_to new_user_registration_url
  end
end

app/helpers/listeners/profiles_helper.rb
module Listeners::ProfilesHelper
end

app/helpers/professionals/profiles_helper.rb
module Professionals::ProfilesHelper
end

app/helpers/professionals/registrations_helper.rb
module Professionals::RegistrationsHelper
end

app/views/professionals/profiles/_profile_fields.slim
/- f.object.listener_sub_genres.build
.nested-fields.profile-wrap
  .row
    .col-md-3
      = f.input :profile_id, autofocus: true, as: :select,
                collection: Profile.pluck(:name, :id), input_html: { class: 'jquery-chosen profile-id'}
      = f.input :profile_name, required: true
    .col-md-9
      div
        = f.simple_fields_for :ip_sub_profiles do |l|
          = render 'professionals/profiles/sub_profile_fields', f: l
        = link_to_add_association content_tag(:i, '', {class: 'fa fa-plus'}) + ' Add More Sub Profile', f, :ip_sub_profiles,
                                partial: 'professionals/profiles/sub_profile_fields', class: 'btn btn-info mrg15B btn-sm add-sub-profile'
  .row
    .col-md-2
      .form-group
        = f.label 'Action + '
        br
        = link_to_remove_association content_tag(:i, ' Remove Profile', {class: 'fa fa-trash-o'}),
                                     f, class: 'btn btn-danger mrg20T btn-sm'
  hr.hr-md

app/views/professionals/profiles/_sub_profile_fields.slim
.nested-fields.sub-profile-wrap
  .row
    .col-md-7
      = f.input :sub_profile_id, required: false, autofocus: true, as: :select,
                collection: (f.object.persisted? ? SubProfile.where(profile_id: f.object.ip_profile.profile_id).pluck(:name, :id) : []), input_html: {class: 'jquery-chosen sub-profile-id'}
    .col-md-5
      .form-group
        = f.label 'Action + '
        br
        = link_to_remove_association content_tag(:i, ' Remove Sub PRofile', {class: 'fa fa-trash-o'}),
                                     f, class: 'btn btn-danger mrg20T btn-sm'
  hr.hr-xs

app/views/professionals/profiles/new.html.slim
.content.container
  .row
    .col-md-8.col-md-offset-2.col-sm-12
      h3 Industry Professional Profile
      = render 'layouts/flash'
      = simple_form_for(@professional_profile, url: professionals_profile_path, html: {class: 'professional-profile-form', method: 'POST'}) do |f|
        = f.input :hireable_lesson,
                  :as => :radio_buttons,
                  :label => "Are You Hirable For Lessons"

        = f.input :hireable_booking,
                  :as => :radio_buttons,
                  :label => "Are You Hirable For Booking"
        .wrap.margin-bottom-20
          h4 Please choose profiles
          = f.simple_fields_for :ip_profiles do |l|
            = render 'professionals/profiles/profile_fields', f: l
          = link_to_add_association content_tag(:i, '', {class: 'fa fa-plus'}) + ' Add More', f, :ip_profiles,
                                      partial: 'professionals/profiles/profile_fields', class: 'btn btn-info mrg15B btn-sm add-genre'
        .form-actions
          = f.button :submit, "Submit"